### ISSUE TITLE
Ignore private ips

### ISSUE THREAD

**Issue by fl4p-old** [jhuckaby/pixl-config#1]
https://github.com/jhuckaby/pixl-config/blob/master/config.js#L250

A check for `172.*` private IPs (used by AWS) is missing here.
See https://en.wikipedia.org/wiki/Private_network

Appropriate function: https://github.com/frenchbread/private-ip/blob/master/src/index.js

**Comment by fl4p-old** [comment]
I had trouble adding a Cronicle slave instance hosted on AWS because it reported its private IP to the master when adding.

**Comment by jhuckaby** [comment]
Hmm, I don't think this is as simple as excluding `172.*`,  because that may be the only available interface on the machine in some cases.

I guess what I have to do is redesign the code to try to find a non-internal non-private interface first, and if none are found, fall back to a middle tier which includes `172.*`, and if that also fails, then fall all the way back to the first interface found.

**Comment by fl4p-old** [comment]
Did you see https://github.com/frenchbread/private-ip/blob/master/src/index.js
?


```
export default (ip) => (
  /^(::f{4}:)?10\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$/i.test(ip) ||
  /^(::f{4}:)?192\.168\.([0-9]{1,3})\.([0-9]{1,3})$/i.test(ip) ||
  /^(::f{4}:)?172\.(1[6-9]|2\d|30|31)\.([0-9]{1,3})\.([0-9]{1,3})$/i.test(ip) ||
  /^(::f{4}:)?127\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$/i.test(ip) ||
  /^(::f{4}:)?169\.254\.([0-9]{1,3})\.([0-9]{1,3})$/i.test(ip) ||
  /^f[cd][0-9a-f]{2}:/i.test(ip) ||
  /^fe80:/i.test(ip) ||
  /^::1$/.test(ip) ||
  /^::$/.test(ip)
)
```

**Comment by jhuckaby** [comment]
Yes, but.... I think there has been a miscommunication here (my fault).  You see, Cronicle is only designed to run on a private LAN, using private internal IPs.  So this module, by design, grabs the first network interface with an IPv4 that is not marked as internal, and doesn't use `169.254.`.  It should most definitely not ever skip over the IPs you have listed there.  In fact, I made a mistake in blindly adding the `172.*` exception, because I didn't understand what you were saying until now.

If you are trying to force Cronicle to connect over a public IP, then what you are asking here isn't going to work.  You need to use the server hostname instead, and configure your DNS setup so it resolves to a public IP.  Cronicle can connect over hostnames instead of IPs:

https://github.com/jhuckaby/Cronicle#server_comm_use_hostnames

### server_comm_use_hostnames

Setting this parameter to `true` will force the Cronicle servers to connect to each other using hostnames rather than LAN IP addresses.  This is mainly for special situations where your local server IP addresses may change, and you would prefer to rely on DNS instead.  The default is `false` (disabled), meaning connect using IP addresses.

Hope this helps.
